(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(fringe-mode 0)
(global-hl-line-mode)
(global-visual-line-mode 1)
(global-ede-mode 1)
;; (partial-completion-mode 1)
(global-font-lock-mode t)
(line-number-mode 1)
(column-number-mode 1)
(transient-mark-mode t)
(delete-selection-mode t)
(global-linum-mode t)
(global-undo-tree-mode 1)
(tabbar-mode 1)
(auto-compression-mode t)
(turn-on-eval-sexp-fu-flash-mode)
(auto-insert-mode t)
(show-paren-mode t)
